### ISSUE TITLE
Provide base16 theme

### ISSUE THREAD

**Issue by prescientmoon** [uloco/bluloco.nvim#53]
Hi!

The terminal themes are nice to have, but it would be even more useful to have a base16 yaml file so we can generate themes for other apps automatically!

**Comment by uloco** [comment]
Hey there! I have two repos of the original vscode themes, where I specify the colors in the readme, see here:
https://github.com/uloco/theme-bluloco-dark
https://github.com/uloco/theme-bluloco-light

But yes we could make a base16 file to make it easier. The problem is though, that the concept of this theme is based on using a lot more accent colors and less shades, to make it more clear and distinct between different scopes of the colors. Don't know how this works out with base 16.
Do you have any idea or suggestion on how to do it or getting started?

**Comment by prescientmoon** [comment]
@uloco I'll give it a try on my machine when I have some time and see if it looks fine without changes

**Comment by prescientmoon** [comment]
Was going on through old notifications when I came across this. I'm not currently super interested in getting this working. If anyone else is interested in base16 themes for this repo, feel free to reopen.
